### ISSUE TITLE
Suggestion on porting

### ISSUE THREAD

**Issue by phkahler** [realtaraharris/solvespace#1]
It looks like you're using native widgets for the toolbar, is that correct? Solvespace only uses the native GUI for creating windows with menus and OpenGL drawing area, as well as simple text input boxes and modal dialogs (all text). All of this should be handled in the single GUI file for a specific platform. The toolbars are just bitmaps rendered via OpenGL, so no need to redo that.

It also seem like you may have jumped the gun on replacing Cairo.  Cairo is strictly used for rendering to files - like SVG or png - and not for the GUI app itself. For that it looks like Cairo should still work on Hauku. If that's true it will save a lot of work.

I hope you are able to do a minimal port to Haiku and send a PR to upstream, that would be really great! Or at least maintain a port here ;-)

**Comment by phkahler** [comment]
Yeah, so looking at the commits on your branch I'm confused unless you're planning to fork solvespace.

The first way to get it running on Haiku would be to use the GTK version since GTK3 works on Haiku AFAICT.

The second way would be to do a native (but as-is) haiku version which should only involve adding a haikuwin.cpp to the platform folder and implementing that abstraction for haiku. Windows, MacOS, and GTK versions all differ in just this one file (and build configuration). IMHO this would be a really nice way to do the port and we would probably accept it upstream. It should also be less work, and you could still base more invasive changes on it if that's what you really want to do.

**Comment by ruevs** [comment]
@phkahler back in April I had the same question. You can read the short "conversation" between @realtaraharris and me here: https://github.com/realtaraharris/solvespace/commit/0e44892bc3c132d4afafaa2de45ee1063b77a35c#r107319428. I think it answers all your questions.

**Comment by realtaraharris** [comment]
@phkahler SolveSpace needs to be restructured to separate the UI from the core; closing
